name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.11"
      - uses: coursier/cache-action@v5
      - name: Unit tests
        run: sbt test
      - name: Scripted tests
        run: sbt scripted
      - name: Build the manual
        run: sbt manual/makeSite
